/**
 * Deterministic anchor ID assignment.
 * IDs are generated by application code before any model call.
 * Format: {docKey}-p{page:03d}-b{block:03d}
 * e.g. "A-p003-b012"
 *
 * For TXT: uses line ranges instead of pages.
 * e.g. "A-l042-b001"
 */

import type { Segment } from "@/types/evidence";

/** Normalize text: strip control chars, collapse whitespace. Never paraphrase. */
export function normalizeText(raw: string): string {
  return raw
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "") // control chars except \t \n \r
    // Remove invisible formatting controls that can disguise prompt injection
    // or make a source passage render differently from what was extracted.
    .replace(/[\u200B-\u200D\u2060\uFEFF\u202A-\u202E\u2066-\u2069]/g, "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Split text into bounded segments (blocks).
 * Each segment is ≤ maxChars characters.
 * Splits on double-newline paragraph boundaries where possible.
 */
export function splitIntoBlocks(
  text: string,
  maxChars = 1200
): string[] {
  if (!Number.isInteger(maxChars) || maxChars < 1) {
    throw new Error("maxChars must be a positive integer");
  }

  const paragraphs = text.split(/\n\n+/);
  const blocks: string[] = [];
  let current = "";

  for (const para of paragraphs) {
    const candidate = current ? `${current}\n\n${para}` : para;
    if (candidate.length <= maxChars) {
      current = candidate;
    } else {
      if (current) blocks.push(current.trim());
      // If a single paragraph is still too long, split by sentences and then
      // by hard bounded chunks. The hard split is important for long clauses
      // without punctuation: no segment may exceed the model budget boundary.
      if (para.length > maxChars) {
        const sentences = para.match(/[^.!?]+(?:[.!?]+|$)/g) || [para];
        let sentBuf = "";
        for (const s of sentences) {
          const sentence = s.trim();
          if (!sentence) continue;
          const candidate = sentBuf ? `${sentBuf} ${sentence}` : sentence;
          if (candidate.length <= maxChars) {
            sentBuf = candidate;
          } else {
            if (sentBuf) blocks.push(sentBuf.trim());
            if (sentence.length > maxChars) {
              blocks.push(...splitLongText(sentence, maxChars));
              sentBuf = "";
            } else {
              sentBuf = sentence;
            }
          }
        }
        if (sentBuf) blocks.push(sentBuf.trim());
        current = "";
      } else {
        current = para;
      }
    }
  }
  if (current.trim()) blocks.push(current.trim());
  return blocks.filter(Boolean);
}

/** Split an oversized string without ever returning a block over maxChars. */
function splitLongText(text: string, maxChars: number): string[] {
  const chunks: string[] = [];
  let remaining = text.trim();

  while (remaining.length > maxChars) {
    let cut = remaining.lastIndexOf(" ", maxChars);
    // Avoid tiny fragments when the nearest whitespace is too early. A hard
    // split is preferable to emitting an unbounded segment.
    if (cut <= 0 || cut < Math.floor(maxChars * 0.5)) cut = maxChars;
    const chunk = remaining.slice(0, cut).trim();
    if (chunk) chunks.push(chunk);
    remaining = remaining.slice(cut).trim();
  }

  if (remaining) chunks.push(remaining);
  return chunks;
}

/**
 * Assign immutable anchor IDs to an array of (locator, blocks) pairs.
 * Returns flat Segment array ready for the evidence index.
 */
export function assignAnchors(
  document: "A" | "B",
  locatedBlocks: Array<{
    locator: string;
    heading?: string;
    blocks: string[];
  }>
): Segment[] {
  const segments: Segment[] = [];
  let blockCounter = 0;

  for (const { locator, heading, blocks } of locatedBlocks) {
    for (const text of blocks) {
      blockCounter++;
      const id = buildAnchorId(document, locator, blockCounter);
      segments.push({ id, document, locator, heading, text });
    }
  }

  return segments;
}

/**
 * Build a stable anchor ID from document key, locator, and sequential block number.
 * Page locators → "A-p003-b012"
 * Line locators → "A-l042-b001"
 * Paragraph locators → "A-g018-b001"
 */
function buildAnchorId(
  document: "A" | "B",
  locator: string,
  blockNum: number
): string {
  const b = String(blockNum).padStart(3, "0");
  const pageMatch = locator.match(/page\s+(\d+)/i);
  if (pageMatch) {
    const p = String(parseInt(pageMatch[1])).padStart(3, "0");
    return `${document}-p${p}-b${b}`;
  }
  const lineMatch = locator.match(/lines?\s+(\d+)/i);
  if (lineMatch) {
    const l = String(parseInt(lineMatch[1])).padStart(3, "0");
    return `${document}-l${l}-b${b}`;
  }
  const paraMatch = locator.match(/paragraph\s+(\d+)/i) || locator.match(/para\s+(\d+)/i);
  if (paraMatch) {
    const g = String(parseInt(paraMatch[1])).padStart(3, "0");
    return `${document}-g${g}-b${b}`;
  }
  // Generic fallback
  return `${document}-x${b}-b${b}`;
}

/** Check a list of anchor IDs against extracted segments. Fails closed on any unknown ID. */
export function checkAnchorAllowlist<T extends { id: string }>(
  anchorIds: string[],
  allowedSegments: T[]
): {
  valid: boolean;
  unknownIds: string[];
  resolved: T[];
} {
  const allowedMap = new Map(allowedSegments.map((s) => [s.id, s]));
  const unknownIds: string[] = [];
  const resolved: T[] = [];

  for (const id of anchorIds) {
    const seg = allowedMap.get(id);
    if (seg) {
      resolved.push(seg);
    } else {
      unknownIds.push(id);
    }
  }

  return {
    valid: unknownIds.length === 0,
    unknownIds,
    resolved,
  };
}
