/**
 * Deterministic anchor ID assignment.
 * IDs are generated by application code before any model call.
 * Format: {docKey}-p{page:03d}-b{block:03d}
 * e.g. "A-p003-b012"
 *
 * For TXT: uses line ranges instead of pages.
 * e.g. "A-l042-b001"
 */

import type { Segment } from "@/types/evidence";

/** Normalize text: strip control chars, collapse whitespace. Never paraphrase. */
export function normalizeText(raw: string): string {
  return raw
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "") // control chars except \t \n \r
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Split text into bounded segments (blocks).
 * Each segment is ≤ maxChars characters.
 * Splits on double-newline paragraph boundaries where possible.
 */
export function splitIntoBlocks(
  text: string,
  maxChars = 1200
): string[] {
  const paragraphs = text.split(/\n\n+/);
  const blocks: string[] = [];
  let current = "";

  for (const para of paragraphs) {
    const candidate = current ? `${current}\n\n${para}` : para;
    if (candidate.length <= maxChars) {
      current = candidate;
    } else {
      if (current) blocks.push(current.trim());
      // If single paragraph is still too long, split by sentences
      if (para.length > maxChars) {
        const sentences = para.match(/[^.!?]+[.!?]+/g) || [para];
        let sentBuf = "";
        for (const s of sentences) {
          if ((sentBuf + s).length <= maxChars) {
            sentBuf += s;
          } else {
            if (sentBuf) blocks.push(sentBuf.trim());
            sentBuf = s;
          }
        }
        if (sentBuf) blocks.push(sentBuf.trim());
        current = "";
      } else {
        current = para;
      }
    }
  }
  if (current.trim()) blocks.push(current.trim());
  return blocks.filter(Boolean);
}

/**
 * Assign immutable anchor IDs to an array of (locator, blocks) pairs.
 * Returns flat Segment array ready for the evidence index.
 */
export function assignAnchors(
  document: "A" | "B",
  locatedBlocks: Array<{
    locator: string;
    heading?: string;
    blocks: string[];
  }>
): Segment[] {
  const segments: Segment[] = [];
  let blockCounter = 0;

  for (const { locator, heading, blocks } of locatedBlocks) {
    for (const text of blocks) {
      blockCounter++;
      const id = buildAnchorId(document, locator, blockCounter);
      segments.push({ id, document, locator, heading, text });
    }
  }

  return segments;
}

/**
 * Build a stable anchor ID from document key, locator, and sequential block number.
 * Page locators → "A-p003-b012"
 * Line locators → "A-l042-b001"
 * Paragraph locators → "A-g018-b001"
 */
function buildAnchorId(
  document: "A" | "B",
  locator: string,
  blockNum: number
): string {
  const b = String(blockNum).padStart(3, "0");
  const pageMatch = locator.match(/page\s+(\d+)/i);
  if (pageMatch) {
    const p = String(parseInt(pageMatch[1])).padStart(3, "0");
    return `${document}-p${p}-b${b}`;
  }
  const lineMatch = locator.match(/lines?\s+(\d+)/i);
  if (lineMatch) {
    const l = String(parseInt(lineMatch[1])).padStart(3, "0");
    return `${document}-l${l}-b${b}`;
  }
  const paraMatch = locator.match(/paragraph\s+(\d+)/i) || locator.match(/para\s+(\d+)/i);
  if (paraMatch) {
    const g = String(parseInt(paraMatch[1])).padStart(3, "0");
    return `${document}-g${g}-b${b}`;
  }
  // Generic fallback
  return `${document}-x${b}-b${b}`;
}
